<?php
/**
 * Single source of truth for the blog listing page, the blog's JSON-LD feed,
 * and the sitemap. Each post's own page still carries its own full <head>
 * metadata and JSON-LD; this array only needs what's required to list it.
 *
 * publish_date controls when a post appears here and in the sitemap, and
 * (via blog_require_published() inside the post's own file) when its URL
 * itself starts returning content instead of a 404. See includes/blog-schedule.php.
 */

const AUTHOR_NAME = 'Risper Murunga, RN, BSN, MPH';

$BLOG_POSTS = [
    [
        'slug' => 'blog-early-signs-of-dementia',
        'title' => "10 Early Warning Signs of Dementia Every Family Should Know",
        'excerpt' => "Cognitive decline rarely arrives all at once. Our Lead Registered Nurse breaks down the subtle early changes in memory, judgment, and mood that families often miss, and the difference it makes to notice them sooner.",
        'image' => 'assets/images/Dementia-Memory-Care.webp',
        'alt' => "Adult daughter gently talking with her aging mother at home",
        'tag_pill' => 'Memory & Dementia Care',
        'publish_date' => '2026-09-10',
        'read_time' => '7 Min Read',
        'featured_eligible' => true,
    ],
    [
        'slug' => 'blog-fall-prevention-checklist',
        'title' => "The Complete Home Fall-Prevention Checklist for Seniors",
        'excerpt' => "A room-by-room walkthrough to identify the hazards that lead to the falls we see most often, and the low-cost fixes that prevent them.",
        'image' => 'assets/images/Fall-Prevention-Home-Safety.webp',
        'alt' => "Grab bar and non-slip mat installed in a senior's bathroom",
        'tag_pill' => 'Home Safety',
        'publish_date' => '2026-09-05',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-hospital-discharge-checklist',
        'title' => "Bringing a Parent Home After Hospital: A Discharge Checklist for Families",
        'excerpt' => "What to arrange in the 48 hours before discharge, so your parent doesn't come home to a gap in care and end up back in the ER.",
        'image' => 'assets/images/photos/lead-registered-nurse-office.jpg',
        'alt' => "Registered nurse reviewing a discharge summary with a clipboard",
        'tag_pill' => 'Hospital to Home',
        'publish_date' => '2026-08-28',
        'read_time' => '8 Min Read',
    ],
    [
        'slug' => 'blog-caregiver-burnout-signs',
        'title' => "Caregiver Burnout: 7 Signs It's Time to Ask for Help",
        'excerpt' => "Exhaustion, resentment, and guilt are common, and treatable. How to recognize burnout in yourself before it affects your health or your parent's care.",
        'image' => 'assets/images/family_care_dialogue.jpg',
        'alt' => "Tired adult daughter sitting with her elderly father",
        'tag_pill' => 'Caregiver Support',
        'publish_date' => '2026-08-20',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-public-vs-private-home-care-bc',
        'title' => "Public vs. Private Home Care in BC: What Vancouver Families Need to Know",
        'excerpt' => "Health authority home support and private home care solve different problems. Here's how the two systems actually compare, and how families often use both.",
        'image' => 'assets/images/hero_elder_care.jpg',
        'alt' => "Senior reviewing home care paperwork with an adult daughter",
        'tag_pill' => 'Funding & Costs',
        'publish_date' => '2026-09-21',
        'read_time' => '9 Min Read',
    ],
    [
        'slug' => 'blog-dementia-vs-normal-aging-signs',
        'title' => "Dementia vs. Normal Aging: How to Tell the Difference",
        'excerpt' => "Not every senior moment is a warning sign. A clear, nurse-led breakdown of what's typical aging and what actually warrants a medical evaluation.",
        'image' => 'assets/images/dementia_cognitive_care.jpg',
        'alt' => "Adult son sitting closely with his aging father, deep in conversation",
        'tag_pill' => 'Memory & Dementia Care',
        'publish_date' => '2026-09-28',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-home-care-cost-vancouver-2026',
        'title' => "How Much Does Home Care Cost in Vancouver? 2026 Price Guide",
        'excerpt' => "Real hourly ranges for companion, personal, and nursing-level home care in Metro Vancouver, and the factors that actually move your price up or down.",
        'image' => 'assets/images/photos/care-team-blood-pressure-check.jpg',
        'alt' => "Caregiver reviewing a home care cost estimate with a client",
        'tag_pill' => 'Funding & Costs',
        'publish_date' => '2026-10-02',
        'read_time' => '10 Min Read',
    ],
    [
        'slug' => 'blog-questions-to-ask-home-care-agency',
        'title' => "10 Questions to Ask Before Choosing a Home Care Agency in Metro Vancouver",
        'excerpt' => "The questions that actually reveal how an agency screens, trains, and supervises its caregivers, before you sign anything.",
        'image' => 'assets/images/photos/care-aide-with-client.jpg',
        'alt' => "Family meeting with a home care coordinator at the kitchen table",
        'tag_pill' => 'Recognizing the Need',
        'publish_date' => '2026-10-09',
        'read_time' => '8 Min Read',
    ],
    [
        'slug' => 'blog-what-is-post-discharge-nursing',
        'title' => "What Is Post-Discharge Nursing and Do You Need It?",
        'excerpt' => "The window right after a hospital stay is when most readmissions happen. Here's what post-discharge nursing actually covers, and who benefits most.",
        'image' => 'assets/images/photos/wound-care-supplies.jpg',
        'alt' => "Registered nurse preparing supplies for a post-discharge home visit",
        'tag_pill' => 'Hospital to Home',
        'publish_date' => '2026-10-16',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-home-care-richmond-bc-guide',
        'title' => "Home Care in Richmond, BC: Services, Costs & How to Get Started",
        'excerpt' => "A local guide for Richmond families: what home care typically costs here, how services work, and how to get a care plan started this week.",
        'image' => 'assets/images/photos/onpoint-community-outreach.jpg',
        'alt' => "Caregiver and senior client outside a Richmond, BC home",
        'tag_pill' => 'Local Care Guide',
        'publish_date' => '2026-10-23',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-bathroom-modifications-fall-prevention',
        'title' => "5 Bathroom Modifications That Prevent Senior Falls at Home",
        'excerpt' => "The bathroom causes more senior falls than any other room. Five changes, most under $150, that meaningfully cut that risk.",
        'image' => 'assets/images/photos/service-fall-prevention.jpg',
        'alt' => "Newly installed grab bar beside a walk-in shower",
        'tag_pill' => 'Home Safety',
        'publish_date' => '2026-10-30',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-talking-to-parent-with-dementia',
        'title' => "How to Talk to a Parent With Dementia: Communication Techniques That Work",
        'excerpt' => "Correcting and reminding often backfires. The specific phrasing and approach our nursing team teaches families instead.",
        'image' => 'assets/images/photos/service-dementia-care.jpg',
        'alt' => "Adult daughter holding her mother's hands and speaking gently",
        'tag_pill' => 'Memory & Dementia Care',
        'publish_date' => '2026-11-03',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-csil-program-bc-explained',
        'title' => "CSIL Explained: Self-Directed Home Care Funding in BC",
        'excerpt' => "Choice in Supports for Independent Living lets eligible clients hire and manage their own care team. How it actually works, and who qualifies.",
        'image' => 'assets/images/photos/onpoint-team-community.jpg',
        'alt' => "Senior signing paperwork with a support worker at home",
        'tag_pill' => 'Funding & Costs',
        'publish_date' => '2026-11-09',
        'read_time' => '8 Min Read',
    ],
    [
        'slug' => 'blog-wound-care-at-home-vs-clinic',
        'title' => "Wound Care at Home vs. Clinic Visits: What's Safer After Surgery?",
        'excerpt' => "Fewer trips, same clinical standard, when it's done right. What to weigh before choosing between at-home wound care and repeat clinic visits.",
        'image' => 'assets/images/Specialized-Wound-Care.webp',
        'alt' => "Registered nurse changing a surgical dressing at a client's home",
        'tag_pill' => 'Hospital to Home',
        'publish_date' => '2026-11-15',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-respite-care-guide-for-caregivers',
        'title' => "Respite Care 101: How to Take a Break Without the Guilt",
        'excerpt' => "Taking a break isn't abandoning your role, it's what makes the role sustainable. How respite care works and how to start small.",
        'image' => 'assets/images/Companionship-Emotional-Support.webp',
        'alt' => "Family caregiver relaxing outdoors while a respite caregiver visits at home",
        'tag_pill' => 'Caregiver Support',
        'publish_date' => '2026-11-21',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-companion-care-loneliness-isolation-seniors',
        'title' => "Companion Care: How It Helps Seniors Fight Loneliness and Isolation",
        'excerpt' => "Isolation carries real health risks for seniors. How regular companion visits rebuild routine, connection, and a reason to look forward to the day.",
        'image' => 'assets/images/photos/service-companionship.jpg',
        'alt' => "Companion caregiver sharing tea and conversation with a senior client",
        'tag_pill' => 'Care Options',
        'publish_date' => '2026-11-27',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-how-to-talk-to-parents-about-home-care',
        'title' => "How to Talk to Aging Parents About Needing Home Care",
        'excerpt' => "The conversation families put off longest. A practical script for raising home care without triggering a fight about independence.",
        'image' => 'assets/images/photos/lead-registered-nurse.jpg',
        'alt' => "Adult child and aging parent having a calm conversation on the couch",
        'tag_pill' => 'Recognizing the Need',
        'publish_date' => '2026-12-03',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-home-care-surrey-bc-guide',
        'title' => "Home Care in Surrey, BC: What Families Should Know",
        'excerpt' => "What to expect from home care in Surrey: typical costs, how quickly care can start, and how to choose the right level of support.",
        'image' => 'assets/images/photos/onpoint-care-team-member.jpg',
        'alt' => "Caregiver assisting a senior client in a Surrey, BC neighborhood",
        'tag_pill' => 'Local Care Guide',
        'publish_date' => '2026-12-09',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-stages-of-dementia-family-guide',
        'title' => "The 7 Stages of Dementia: A Family Guide to What to Expect",
        'excerpt' => "Knowing what's coming next helps families plan instead of react. A clear walkthrough of each stage and the care needs that go with it.",
        'image' => 'assets/images/photos/care-story-dementia-respite.jpg',
        'alt' => "Family looking through old photos with a parent living with dementia",
        'tag_pill' => 'Memory & Dementia Care',
        'publish_date' => '2026-12-15',
        'read_time' => '9 Min Read',
    ],
    [
        'slug' => 'blog-preventing-hospital-readmission-seniors',
        'title' => "Preventing Hospital Readmission: What Families Can Do at Home",
        'excerpt' => "Nearly one in five senior hospital stays ends in readmission within a month. The at-home habits that meaningfully lower that risk.",
        'image' => 'assets/images/Nursing-Health-Monitoring.webp',
        'alt' => "Nurse reviewing a medication schedule with a senior client at home",
        'tag_pill' => 'Hospital to Home',
        'publish_date' => '2026-12-21',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-home-care-tax-credits-canada',
        'title' => "Is Home Care Tax Deductible in Canada? Credits Families Can Claim",
        'excerpt' => "Several federal and BC credits can offset home care costs, but the eligibility rules trip up most families. Here's what actually qualifies.",
        'image' => 'assets/images/photos/client-thank-you-gift.jpg',
        'alt' => "Family reviewing tax documents and receipts at the kitchen table",
        'tag_pill' => 'Funding & Costs',
        'publish_date' => '2026-12-28',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-signs-elderly-parent-needs-help',
        'title' => "Independent But Struggling: Recognizing the Early Signs Your Parent Needs Support",
        'excerpt' => "Parents who insist they're fine can still be quietly struggling. The subtle household and self-care signs worth paying attention to.",
        'image' => 'assets/images/nurse_checking_vitals.jpg',
        'alt' => "Adult daughter noticing unopened mail while visiting her father",
        'tag_pill' => 'Recognizing the Need',
        'publish_date' => '2027-01-04',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-24-hour-nursing-vs-home-care',
        'title' => "24-Hour Nursing Care vs. 24-Hour Home Care: What's the Difference?",
        'excerpt' => "Both provide round-the-clock coverage, but the clinical scope is very different. How to know which level your family actually needs.",
        'image' => 'assets/images/photos/service-nursing-monitoring.jpg',
        'alt' => "Registered nurse checking vitals during an overnight home visit",
        'tag_pill' => 'Hospital to Home',
        'publish_date' => '2027-01-10',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-sundowning-dementia-explained',
        'title' => "Sundowning Explained: Why Dementia Symptoms Worsen at Night",
        'excerpt' => "Late-afternoon agitation and confusion are common in dementia, and largely manageable. What triggers sundowning and how to ease it.",
        'image' => 'assets/images/Dementia-Memory-Care.webp',
        'alt' => "Senior with dementia looking out the window at dusk",
        'tag_pill' => 'Memory & Dementia Care',
        'publish_date' => '2027-01-16',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-home-care-burnaby-bc-guide',
        'title' => "Home Care in Burnaby, BC: Services & Local Support for Seniors",
        'excerpt' => "A Burnaby-focused look at home care services, typical costs, and how families in the area can get started quickly.",
        'image' => 'assets/images/photos/onpoint-team-community.jpg',
        'alt' => "Caregiver walking with a senior client in a Burnaby, BC park",
        'tag_pill' => 'Local Care Guide',
        'publish_date' => '2027-01-22',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-overnight-care-vs-24-hour-care',
        'title' => "Overnight Care vs. 24-Hour Care: Which Does Your Parent Actually Need?",
        'excerpt' => "Paying for round-the-clock coverage when overnight support would do (or the reverse) is a common, costly mismatch. How to tell which fits.",
        'image' => 'assets/images/photos/lead-registered-nurse-office.jpg',
        'alt' => "Overnight caregiver checking in on a sleeping senior client",
        'tag_pill' => 'Care Options',
        'publish_date' => '2027-01-28',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-fall-recovery-first-30-days',
        'title' => "Fall Recovery at Home: What the First 30 Days Should Look Like",
        'excerpt' => "The first month after a fall shapes long-term recovery and confidence. A week-by-week look at what care should focus on.",
        'image' => 'assets/images/photos/service-fall-prevention.jpg',
        'alt' => "Physiotherapist assisting a senior with mobility exercises at home",
        'tag_pill' => 'Home Safety',
        'publish_date' => '2027-02-03',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-24-hour-vs-live-in-care-cost',
        'title' => "24-Hour Care vs. Live-In Care: Cost & Coverage Differences Explained",
        'excerpt' => "The two are often confused, and priced very differently. A clear cost and coverage comparison to help you budget accurately.",
        'image' => 'assets/images/photos/care-team-blood-pressure-check.jpg',
        'alt' => "Caregiver and senior client reviewing a weekly care schedule",
        'tag_pill' => 'Funding & Costs',
        'publish_date' => '2027-02-09',
        'read_time' => '8 Min Read',
    ],
    [
        'slug' => 'blog-sibling-conflict-elderly-parent-care',
        'title' => "Sibling Conflict Over Parent Care: How to Get Everyone on the Same Page",
        'excerpt' => "Old family roles resurface fast under care stress. A practical framework for dividing responsibility without the resentment.",
        'image' => 'assets/images/family_care_dialogue.jpg',
        'alt' => "Adult siblings having a serious conversation about a parent's care",
        'tag_pill' => 'Caregiver Support',
        'publish_date' => '2027-02-15',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-chronic-disease-management-home-nursing',
        'title' => "Managing Chronic Conditions at Home: CHF, COPD & Diabetes Nursing Support",
        'excerpt' => "Consistent at-home nursing monitoring catches the small changes that prevent CHF, COPD, and diabetes complications from becoming ER visits.",
        'image' => 'assets/images/Nursing-Health-Monitoring.webp',
        'alt' => "Nurse monitoring blood glucose levels for a senior client at home",
        'tag_pill' => 'Hospital to Home',
        'publish_date' => '2027-02-21',
        'read_time' => '8 Min Read',
    ],
    [
        'slug' => 'blog-independent-home-care-small-supports',
        'title' => "Independent Home Care: Small Supports That Keep Seniors Self-Sufficient",
        'excerpt' => "Independence isn't all-or-nothing. The light-touch supports that let seniors keep doing things themselves, safely, for longer.",
        'image' => 'assets/images/Personal-Care-Daily-Living.webp',
        'alt' => "Senior independently preparing a meal with light caregiver support nearby",
        'tag_pill' => 'Care Options',
        'publish_date' => '2027-02-27',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-dementia-home-care-vs-facility',
        'title' => "Choosing Between Home Dementia Care and Memory Care Facilities",
        'excerpt' => "Both can provide excellent care. The honest tradeoffs between staying home with support and moving into a memory care facility.",
        'image' => 'assets/images/photos/onpoint-care-team-member.jpg',
        'alt' => "Family discussing dementia care options with a nurse at home",
        'tag_pill' => 'Memory & Dementia Care',
        'publish_date' => '2027-03-05',
        'read_time' => '9 Min Read',
    ],
    [
        'slug' => 'blog-home-care-new-westminster-guide',
        'title' => "Home Care in New Westminster, BC: A Family's Guide",
        'excerpt' => "Everything New Westminster families need to know about starting home care: costs, timelines, and how service actually works.",
        'image' => 'assets/images/photos/care-aide-with-client.jpg',
        'alt' => "Caregiver and senior client outside a New Westminster, BC home",
        'tag_pill' => 'Local Care Guide',
        'publish_date' => '2027-03-11',
        'read_time' => '6 Min Read',
    ],
    [
        'slug' => 'blog-aging-in-place-home-safety-assessment',
        'title' => "Aging in Place: Is Your Parent's Home Actually Safe for the Long Term?",
        'excerpt' => "A thorough, room-by-room way to evaluate whether a longtime family home can genuinely support aging in place, and what to change if it can't.",
        'image' => 'assets/images/photos/service-fall-prevention.jpg',
        'alt' => "Occupational therapist assessing a senior's home for safety hazards",
        'tag_pill' => 'Home Safety',
        'publish_date' => '2027-03-17',
        'read_time' => '7 Min Read',
    ],
    [
        'slug' => 'blog-companion-vs-personal-vs-nursing-care',
        'title' => "Companion Care vs. Personal Care vs. Nursing Care: What's the Difference (and Cost)?",
        'excerpt' => "Three distinct levels of care, three different price points. A side-by-side comparison to help you choose the right starting point.",
        'image' => 'assets/images/Personal-Care-Daily-Living.webp',
        'alt' => "Three caregivers representing different levels of home care support",
        'tag_pill' => 'Care Options',
        'publish_date' => '2027-03-23',
        'read_time' => '8 Min Read',
    ],
    [
        'slug' => 'blog-complex-care-at-home-guide',
        'title' => "Complex Care at Home: When a Senior Needs More Than Basic Support",
        'excerpt' => "When multiple conditions, medications, or mobility needs stack up, care needs change. The signs it's time to step up to complex care.",
        'image' => 'assets/images/photos/service-wound-care.jpg',
        'alt' => "Nurse coordinating complex care needs for a senior client at home",
        'tag_pill' => 'Care Options',
        'publish_date' => '2027-03-29',
        'read_time' => '7 Min Read',
    ],
];
